### ISSUE TITLE
[Suggestion] Repurpose Heroic Game Launcher UI

### ISSUE THREAD

**Issue by nikitperiwal** [CarrotRub/Fit-Launcher#17]
Instead of building a custom UI, consider repurposing the existing Heroic Game Launcher UI. It’s a proven, stable, and user-friendly interface developed to run seamlessly across multiple operating systems, including Windows, macOS, and Linux. The UI is already optimized for functionality, providing a polished user experience. Adopting this approach would save significant development time, reduce overhead, and leverage a battle-tested design, allowing the team to focus on enhancing core functionality rather than reinventing the interface.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/

**Comment by CarrotRub** [comment]
The whole launcher is already there, we are working on bug fixing etc but we are already too far into development to make any major system change, especially since we aren't using anything related to the Heroic Games Launcher, thus we would have to translate every inch of code and it would be harder than just fixing bugs and adding features.

I will still take a look at some features of the Heroic Games Launcher and probably try to implement them into our code base.
