### ISSUE TITLE
Error 2502 and 2503

### ISSUE THREAD

**Issue by DKLAZ** [CarrotRub/Fit-Launcher#2]
![image](https://github.com/user-attachments/assets/d6922fe9-48c1-41b2-b4bc-651755789501)

**Comment by CarrotRub** [comment]
It may either be caused by you not owning the folder (not being an admin) or if you have a thirdparty antivirus, refer to this link for more information as it is an error related to windows and not specific to my app :
https://answers.microsoft.com/en-us/windows/forum/all/error-code-2502-and-2503-when-installing/f5a72c98-0fe9-40f9-bcd6-5240c0e33393
